name: RELEASE

on:
  push:
    tags:
     - '*'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: graalvm/setup-graalvm@v1
        with:
          version: '21.3.0'
          java-version: '11'
          components: 'native-image'
          github-token: ${{ secrets.GITHUB_TOKEN }}
      - name: Build native image
        run: mvn package
      - name: Upload package
        uses: actions/upload-artifact@v3
        with:
          name: graalvm-image
          path: target/graalvm-actions-demo
